### ISSUE TITLE
DLC Content

### ISSUE THREAD

**Issue by Kaciej12** [arthurb123/ERregulator#2]
This tool is so cool but does it support dlc content? Will this get updated, or should it actually work even with the dlc content?
I'm wondering if it shuffles universal param values, like per category, or are the param values individual for each weapon/armor etc?
I'm new to modding but I'd really like to understand it more.

**Comment by arthurb123** [comment]
Hello. Sorry for the late answer. I saw your comment in another issue and [replied to it](https://github.com/arthurb123/ERregulator/issues/3#issuecomment-2317226435) regarding updating the randomizer to support the new DLC content. 
As for the shuffling, the primary method of randomization in this mod is by shuffling parameter values inside categories (thus, weapons will shuffle parameter values with other weapons, same for equipment, talismans, etc). 
For weapons, there is a bit more nuance. Because weapons, as a category, can have subcategories (swords, staves, axes). This is why there exists an option called _"Keep Categories"_ in the _"Weapons"_ section of the mod, in case people don't want staves to possibly get move sets or arts of war from axes or bows.
If you would like to learn more, I am afraid I can't link you to any useful resources as I created this mod solely by looking at JK Anderson's [Irregulator for Dark Souls 3](https://github.com/JKAnderson/Irregulator) and modified it for Elden Ring. This is my first ever souls-game mod and I just learned as I went. Therefore, I can only recommend you look at the source code and try to get a better understanding of that :)

**Comment by arthurb123** [comment]
The randomizer has been updated to support the DLC. The new release can be found [on the releases page listed as version 2.0](https://github.com/arthurb123/ERregulator/releases/tag/v2.0). I will be closing this issue, if you have any other questions regarding the new release please create a new issue.
